### PR TITLE
fix response undefined error

### LINKED ISSUE #96: Connection got disposed
image
Output channel info
image

### PR DESCRIPTION
**Pull request by jdneo**
fix #96

### CODE REVIEW

File: server/src/downloadCheckstyle.ts [hunk 1]
```diff
@@ -65,7 +65,7 @@ export async function downloadCheckstyle(connection: any, downloadPath: string,
     });
 }
 
-async function isValidVersionNumber(url: string): Promise<boolean> {
+async function isValidVersionNumber(url: string, connection: any, textDocumentUri: string): Promise<boolean> {
```
Comment (Eskibear) [inline server/src/downloadCheckstyle.ts]: Is it confusing to add these params to such a util function?
