### PR TITLE
fix: Support listening to configuration file outside of workspace

### LINKED ISSUE #209: Check style rule file(outside of current WS) change will not be reflected

### PR DESCRIPTION
**Pull request by Vigilans**
Fix #209

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -71,6 +69,7 @@ async function doActivate(_operationId: string, context: ExtensionContext): Prom
         checkstyleStatusBar,
         checkstyleDiagnosticManager,
         codeWatcher,
+        { dispose: (): void => { configWatcher!.close(); } },
```
Comment (jdneo) [inline src/extension.ts]: remove `!`
