### PR TITLE
fix: Refresh server when configuration file is created, changed or deleted

### LINKED ISSUE #203: Cannot synchronize checkstyle config file changes in real time
**Description:**
When a user changes the config in checkstyle.xml, the plugin can't sync in real time. User should reload window or restart vscode to enable the changed config.
This is a regression issue, can synchronize checkstyle config file changes in real time in the previous version.

**Reproduce Step:**
1. Clone and using vscode open https://github.com/Microsoft/todo-app-java-on-azure.git
2. Set the Checkstyle configuration file in the file explorer by Select Set the Checkstyle
3. Right-click a folder, selecting Check Code with Checkstyle
4. Verity checkstyle diagnostics in problem panel and comment a config in checkstyle config file
5. Verify the commented config can still diagnostic
6. Execute Developer: Reload Window in the command palette
7. The commented config can not diagnostic

**Environments:**

- OS: Windows 10
- VS Code version: 1.36.1
- Extension version; 1.1.0

### PR DESCRIPTION
**Pull request by Vigilans**
Fix #203

### CODE REVIEW

File: src/features/FileSynchronizer.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ import { checkstyleChannel } from '../checkstyleChannel';
 
 export class SyncedFile {
     constructor(
-        private readonly document: vscode.TextDocument,
+        public readonly document: vscode.TextDocument,
```
Comment (jdneo) [inline src/features/FileSynchronizer.ts]: Keep it private and provide a getter.
